# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="custom_visit_usage",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="visitor",
            name="visit_usage",
            field=models.CharField(
                choices=[
                    ("MEETING", "MEETING"),
                    ("DELIVERY", "DELIVERY"),
                    ("INTERVIEW", "INTERVIEW"),
                    ("MAINTENANCE", "MAINTENANCE"),
                    ("OFFICIAL", "OFFICIAL"),
                    ("CUSTOM", "CUSTOM"),
                ],
                db_index=True,
                default="MEETING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="check_out_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
