# Generated by Django 5.2.14 on 2026-06-14 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_options_alter_device_last_seen_and_more'),
        ('visitors', '0002_visit_usage_and_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'CHECK_IN'), ('ACCESS_GRANTED', 'ACCESS_GRANTED'), ('ACCESS_DENIED', 'ACCESS_DENIED')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
