# Generated by Django 5.2.14 on 2026-05-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('MAINTENANCE', 'MAINTENANCE')], db_index=True, default='OFFLINE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen'], name='devices_dev_last_se_66ef2a_idx'),
        ),
    ]
