# Generated by Codex on 2026-06-14

import uuid

import django.db.models.deletion
from django.db import migrations, models


def populate_device_api_keys(apps, schema_editor):
    Device = apps.get_model("devices", "Device")

    for device in Device.objects.filter(api_key__isnull=True):
        device.api_key = uuid.uuid4().hex
        device.save(update_fields=["api_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_options_alter_device_last_seen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="api_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(populate_device_api_keys, migrations.RunPython.noop),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS devices_device_api_key_8572417b_like",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="device",
            name="api_key",
            field=models.CharField(
                default=uuid.uuid4, max_length=64, unique=True
            ),
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("UNLOCK", "UNLOCK"),
                            ("LOCK", "LOCK"),
                            ("SYNC", "SYNC"),
                            ("RESTART", "RESTART"),
                            ("BUZZER", "BUZZER"),
                            ("DISPLAY_MESSAGE", "DISPLAY_MESSAGE"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SENT", "SENT"),
                            ("ACKNOWLEDGED", "ACKNOWLEDGED"),
                            ("FAILED", "FAILED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("response_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "status"],
                        name="devices_dev_device__0a9c1c_idx",
                    ),
                    models.Index(
                        fields=["command_type"],
                        name="devices_dev_command_d6e294_idx",
                    ),
                ],
            },
        ),
    ]
