# Generated by Django 5.2.14 on 2026-05-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_alter_device_options_alter_device_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('employee_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rfid_uid', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('fingerprint_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('access_level', models.CharField(choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('SECURITY', 'SECURITY'), ('CONTRACTOR', 'CONTRACTOR')], db_index=True, default='STAFF', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_method', models.CharField(choices=[('RFID', 'RFID'), ('FINGERPRINT', 'FINGERPRINT'), ('REMOTE', 'REMOTE'), ('MANUAL', 'MANUAL')], db_index=True, max_length=30)),
                ('access_result', models.CharField(choices=[('GRANTED', 'GRANTED'), ('DENIED', 'DENIED')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.accessperson')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='access_acce_timesta_8592ee_idx'), models.Index(fields=['access_result'], name='access_acce_access__7d7ec5_idx')],
            },
        ),
    ]
