# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessperson",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="accessperson",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("STAFF", "STAFF"),
                    ("VISITOR", "VISITOR"),
                    ("OFFICE_WORKER", "OFFICE_WORKER"),
                    ("CONTRACTOR", "CONTRACTOR"),
                    ("SECURITY", "SECURITY"),
                    ("OTHER", "OTHER"),
                ],
                db_index=True,
                default="STAFF",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="accessperson",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="accessperson",
            name="employee_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
