# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_accessperson_contact_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessevent",
            name="auth_method",
            field=models.CharField(
                choices=[
                    ("RFID", "RFID"),
                    ("FINGERPRINT", "FINGERPRINT"),
                    ("VISITOR_CODE", "VISITOR_CODE"),
                    ("REMOTE", "REMOTE"),
                    ("MANUAL", "MANUAL"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
